[package]
name = "bevy_mod_actuate"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A reactive user-interface framework"
repository = "https://github.com/actuate-rs/bevy_mod_actuate"

[dependencies]
